
USE AGREGADOS;

/*EJERCICIO 1*/

DELIMITER //
CREATE PROCEDURE EJERCICIO1()
BEGIN
select *  from material where precio >= 20 and precio <=50;
END//
DELIMITER ;

/*EJERCICIO 2*/
DELIMITER //
CREATE PROCEDURE EJERCICIO2()
BEGIN
SELECT * FROM MATERIAL WHERE DESCRIPCION LIKE 'A%';
END//
DELIMITER ;

-- EJERCICIO 3

DELIMITER $$
CREATE PROCEDURE EJERCICIO3()
BEGIN
SELECT M.DESCRIPCION AS MATERIAL, AVG(S.CANTIDAD) AS 'CANTIDAD PROMEDIO' FROM
MATERIAL M INNER JOIN SOLICITUD S ON S.CODIGO = M.CODIGO
WHERE MONTH(S.FECHA) = 12 AND YEAR(S.FECHA) = 2022 GROUP BY DESCRIPCION;
END $$
DELIMITER ;


-- EJERICIO 4

DELIMITER $$
  CREATE PROCEDURE PAEJERCICIO4()
  BEGIN
  SELECT M.DESCRIPCION AS MATERIAL, SUM(S.CANTIDAD) AS 'CANTIDAD TOTAL' FROM
  MATERIAL M INNER JOIN SOLICITUD S ON S.CODIGO = M.CODIGO
  WHERE M.PRECIO > 5 GROUP BY DESCRIPCION;
  END $$
DELIMITER ;

CALL PAEJERCICIO4();

-- EJERCICIO 5

DELIMITER $$
CREATE PROCEDURE PAEJERCICIO5()
BEGIN
	SELECT M.DESCRIPCION AS MATERIAL, D.CSALDO AS SALDO FROM
    MATERIAL M INNER JOIN DEPOSITO D ON D.CODIGO = M.CODIGO
    WHERE D.CSALDO > 0 ORDER BY M.DESCRIPCION ASC;
END $$
DELIMITER ;

CALL PAEJERCICIO5();



-- EJERCICIO 6

DELIMITER $$
	CREATE PROCEDURE PAEJERCICIO6()
		BEGIN
			SELECT M.DESCRIPCION AS 'MATERIAL', SUM(S.CANTIDAD * M.PRECIO) AS 'COSTO TOTAL' FROM
            MATERIAL M INNER JOIN SOLICITUD S ON M.CODIGO =  S.CODIGO WHERE
            YEAR(S.FECHA) = 2022 GROUP BY M.DESCRIPCION HAVING COUNT(S.CANTIDAD >=2);
		END $$
DELIMITER ;
DROP PROCEDURE PAEJERCICIO6;

 SELECT * FROM SOLICITUD;

CALL PAEJERCICIO6();

-- EJERCICIO 7

DELIMITER $$
	CREATE PROCEDURE PAEJERCICIO7()
		BEGIN
			SELECT DESCRIPCION AS 'MATERIAL', PRECIO AS 'COSTO' FROM
            MATERIAL WHERE DESCRIPCION = ENUM('A%' , 'B%', 'C%', 'D%', 'E%');
			
        END $$
DELIMITER ;

