USE AGREGADOS;

/*EJERCICIO 1*/

DELIMITER //
CREATE PROCEDURE EJERCICIO1()
BEGIN
select *  from material where precio >= 20 and precio <=50;
END//
DELIMITER ;

/*EJERCICIO 2*/
DELIMITER //
CREATE PROCEDURE EJERCICIO2()
BEGIN
SELECT * FROM MATERIAL WHERE DESCRIPCION LIKE 'A%';
END//
DELIMITER ;