CREATE DATABASE COMPRAS
CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;

USE COMPRAS;

CREATE TABLE EMPRESA(
NITEMP CHAR(14) NOT NULL PRIMARY KEY,
NOMBREEMP VARCHAR(35) DEFAULT '',
TELEFONOEMP INT DEFAULT 0,
DERECCIONEMP VARCHAR(30) DEFAULT ''
)ENGINE = INNODB;

CREATE TABLE SUCURSAL (
NITEMP CHAR(14) NOT NULL PRIMARY KEY,
CIUDAD VARCHAR(25) DEFAULT '',
DIRECCIONSUC VARCHAR(35) DEFAULT '',
TELEFONOSUC INT(8) DEFAULT 0,
FOREIGN KEY (NITEMP) REFERENCES EMPRESA(NITEMP)
) ENGINE = INNODB;


CREATE TABLE ARTICULO (
CODART CHAR(6) NOT NULL PRIMARY KEY,
DESCRIPCION VARCHAR(35) DEFAULT '',
UNIDADMEDIDA CHAR(4) DEFAULT '',
PRECIO FLOAT, CHECK(PRECIO > 0.0)
) ENGINE = INNODB;

CREATE TABLE PERSONAL (
ITEMPER INT NOT NULL PRIMARY KEY,
NOMBREPER VARCHAR(35)  DEFAULT '',
EDAD INT, CHECK(EDAD > 0),
SEXO CHAR(1), CHECK(SEXO IN('F', 'M')),
FECHAINGRESO DATETIME,
NITEMP CHAR(14),
FOREIGN KEY (NITEMP) REFERENCES EMPRESA(NITEMP)
) ENGINE = INNODB;

CREATE TABLE SOLICITUD(
NUMSOL INT(4) NOT NULL PRIMARY KEY,
FECHASOL DATETIME DEFAULT NOW(),
CANTIDADSOL INT(6), CHECK (CANTIDADSOL > 0),
ST CHAR(1) DEFAULT '',
ITEMPER INT(6),
CODART CHAR(6),
FOREIGN KEY (ITEMPER) REFERENCES PERSONAL(ITEMPER),
FOREIGN KEY (CODART) REFERENCES ARTICULO(CODART)
)ENGINE = INNODB;

CREATE TABLE COMPRA(
CODART CHAR(6) NOT NULL,
NITEMP CHAR(14) NOT NULL,
CANTIDAD INT(6), CHECK(CANTIDAD > 0),
COSTOTOTAL FLOAT, CHECK(COSTOTOTAL > 0.0),
NUMSOL INT(4), PRIMARY KEY(CODART, NITEMP),
FOREIGN KEY (CODART) REFERENCES ARTICULO(CODART),
FOREIGN KEY (NITEMP) REFERENCES EMPRESA(NITEMP),
FOREIGN KEY (NUMSOL) REFERENCES SOLICITUD(NUMSOL)
) ENGINE = INNODB;